name: Test Node.js Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test-secrets:
    runs-on: self-hosted
    env:
      CUSTOM_VARIABLE: "This is a GitHub variable."

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run the Server with Secrets
      - name: Start Backend and Test Secrets
        env: # Inject secrets into environment variables
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          CUSTOM_VARIABLE: ${{ env.CUSTOM_VARIABLE }}
        run: |
          node index.js & # Start the server in the background
          sleep 5 # Allow the server to start
          curl http://localhost:3000 # Test the endpoint

      # Step 5: Validate Response
      - name: Validate Secrets in Response
        run: |
          RESPONSE=$(curl -s http://localhost:3000)
          echo "Response: $RESPONSE"
          if [[ $RESPONSE != *"Secrets retrieved successfully."* ]]; then
            echo "Secrets not fetched correctly!" && exit 1
          fi
