name: Test Node.js Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  test-secrets:
    runs-on: self-hosted
    env:
      CUSTOM_VARIABLE: "This is a GitHub variable."

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Export Secrets to Environment Permanently
      - name: Export Secrets to Environment
        run: |
          echo "SECRET_API_KEY=${{ secrets.SECRET_API_KEY }}" >> ~/.bashrc
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ~/.bashrc
          echo "CUSTOM_VARIABLE=${{ env.CUSTOM_VARIABLE }}" >> ~/.bashrc
          source ~/.bashrc
          echo "Secrets exported to ~/.bashrc"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Start the Server with Secrets
      - name: Start Backend and Test Secrets
        run: |
          source ~/.bashrc # Ensure environment variables are loaded
          node index.js & # Start the server in the background
          sleep 5 # Allow the server to start
          curl http://localhost:3000 # Test the endpoint

      # Step 5: Validate Response
      - name: Validate Secrets in Response
        run: |
          source ~/.bashrc # Ensure environment variables are loaded
          RESPONSE=$(curl -s http://localhost:3000)
          echo "Response: $RESPONSE"
          if [[ $RESPONSE != *"Secrets retrieved successfully."* ]]; then
            echo "Secrets not fetched correctly!" && exit 1
          fi
